# Generated by Django 5.2.2 on 2025-06-13 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenen Tutar')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Kredi Kartı'), ('bank_transfer', 'Banka Havalesi'), ('cash', 'Nakit'), ('other', 'Diğer')], default='credit_card', max_length=20, verbose_name='Ödeme Yöntemi')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
                ('expert_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Uzman Komisyonu')),
                ('agent_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Temsilci Komisyonu')),
                ('is_commission_calculated', models.BooleanField(default=False, verbose_name='Komisyon Hesaplandı mı?')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment', verbose_name='Randevu')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-payment_date'],
            },
        ),
    ]
