# Generated by Django 5.2.2 on 2025-06-19 09:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_service_type'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Randevudan temsilciye ödenecek komisyon tutarı.', max_digits=10, verbose_name='Temsilci Komisyonu'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Müşteri tarafından ödenen gerçek tutar.', max_digits=10, verbose_name='Ödenen Tutar'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(help_text='Bu ödemenin ilişkili olduğu randevu.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment', verbose_name='Randevu'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expert_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Randevudan uzmana ödenecek komisyon tutarı.', max_digits=10, verbose_name='Uzman Komisyonu'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_commission_calculated',
            field=models.BooleanField(default=False, help_text='Komisyonların bu ödeme için hesaplanıp hesaplanmadığını belirtir.', verbose_name='Komisyon Hesaplandı mı?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Ödemenin kaydedildiği tarih ve saat.', verbose_name='Ödeme Tarihi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Kredi Kartı'), ('bank_transfer', 'Banka Havalesi'), ('cash', 'Nakit'), ('other', 'Diğer')], default='credit_card', help_text='Ödemenin yapıldığı yöntem.', max_length=20, verbose_name='Ödeme Yöntemi'),
        ),
    ]
