# Generated by Django 5.2.2 on 2025-06-09 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragent',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'client'}, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
