# Generated by Django 5.2.2 on 2025-06-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeragent_assigned_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeragent',
            options={'verbose_name': 'Müşteri Temsilcisi', 'verbose_name_plural': 'Müşteri Temsilcileri'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Uzman', 'verbose_name_plural': 'Uzmanlar'},
        ),
    ]
