# Generated by Django 5.2.2 on 2025-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customeragent_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Örn: 5551234567', max_length=15, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Yönetici'), ('expert', 'Uzman'), ('agent', 'Müşteri Temsilcisi'), ('client', 'Müşteri')], default='client', max_length=10, verbose_name='Kullanıcı Türü'),
        ),
    ]
