# Generated by Django 5.2.2 on 2025-06-09 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeragent',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'client'}, related_name='agents', to=settings.AUTH_USER_MODEL, verbose_name='Atanmış Müşteriler'),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='commission_rate',
            field=models.FloatField(default=0.2, verbose_name='Komisyon Oranı'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='commission_rate',
            field=models.FloatField(default=0.3, verbose_name='Komisyon Oranı'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='specialization',
            field=models.CharField(max_length=100, verbose_name='Uzmanlık Alanı'),
        ),
    ]
