# Generated by Django 5.2.2 on 2025-06-15 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customeragent_assigned_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeragent',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5, verbose_name='Komisyon Oranı'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=5, verbose_name='Komisyon Oranı'),
        ),
    ]
