# Generated by Django 5.2.2 on 2025-06-22 19:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customeragent_supervisor_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragent',
            name='supervisor_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_agents', to='accounts.customeragent', verbose_name='Üst Temsilci'),
        ),
        migrations.AddField(
            model_name='customeragent',
            name='supervisor_commission_share_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), help_text='Alt temsilcinin kazancından alacağı yüzde.', max_digits=5, verbose_name='Üst Temsilci Komisyon Payı Oranı'),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5, verbose_name='Kendi Komisyon Oranı'),
        ),
    ]
