# Generated by Django 5.2.2 on 2025-06-22 19:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customeragent_supervisor_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeragent',
            name='supervisor_agent',
        ),
        migrations.RemoveField(
            model_name='customeragent',
            name='supervisor_commission_share_rate',
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5, verbose_name='Komisyon Oranı'),
        ),
    ]
