# Generated by Django 5.2.2 on 2025-06-22 19:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customeragent_supervisor_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragent',
            name='alt_temsilci_komisyon_orani',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=5, verbose_name='Alt Temsilci Komisyon Oranı'),
        ),
        migrations.AddField(
            model_name='customeragent',
            name='ust_temsilci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_temsilciler', to='accounts.customeragent', verbose_name='Üst Temsilci'),
        ),
    ]
