# Generated by Django 5.2.2 on 2025-06-25 18:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customeragent_alt_temsilci_komisyon_orani_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeragent',
            name='alt_temsilci_komisyon_orani',
        ),
        migrations.RemoveField(
            model_name='customeragent',
            name='assigned_clients',
        ),
        migrations.RemoveField(
            model_name='customeragent',
            name='ust_temsilci',
        ),
        migrations.AddField(
            model_name='customeragent',
            name='parent_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_agents', to='accounts.customeragent', verbose_name='Üst Temsilci'),
        ),
        migrations.AddField(
            model_name='customeragent',
            name='sub_agent_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=5, verbose_name='Alt Temsilci Gelir Payı Oranı'),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5, verbose_name='Kendi Komisyon Oranı'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_transactions', to='accounts.customeragent', verbose_name='İlgili Temsilci')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
