# Generated by Django 5.2.2 on 2025-06-25 18:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customeragent_alt_temsilci_komisyon_orani_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeragent',
            name='parent_agent',
        ),
        migrations.RemoveField(
            model_name='customeragent',
            name='sub_agent_commission_rate',
        ),
        migrations.AddField(
            model_name='customeragent',
            name='alt_temsilci_komisyon_orani',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=5, verbose_name='Alt Temsilci Komisyon Oranı'),
        ),
        migrations.AddField(
            model_name='customeragent',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'client'}, related_name='agents', to=settings.AUTH_USER_MODEL, verbose_name='Atanmış Müşteriler'),
        ),
        migrations.AddField(
            model_name='customeragent',
            name='ust_temsilci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_temsilciler', to='accounts.customeragent', verbose_name='Üst Temsilci'),
        ),
        migrations.AlterField(
            model_name='customeragent',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5, verbose_name='Komisyon Oranı'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
