# Generated by Django 5.2.2 on 2025-06-09 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customeragent_assigned_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Randevu Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı')], default='pending', max_length=10, verbose_name='Durum')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Ödeme Durumu')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customeragent', verbose_name='Temsilci')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.expert', verbose_name='Uzman')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['-date'],
            },
        ),
    ]
