# Generated by Django 5.2.2 on 2025-06-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customeragent_assigned_clients_and_more'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.expert', verbose_name='Uzman')),
            ],
            options={
                'verbose_name': 'Uzman Tatil/İzin',
                'verbose_name_plural': 'Uzman Tatil/İzinleri',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpertAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Haftanın Günü')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.expert', verbose_name='Uzman')),
            ],
            options={
                'verbose_name': 'Uzman Müsaitlik',
                'verbose_name_plural': 'Uzman Müsaitlikleri',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('expert', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
