# Generated by Django 5.2.2 on 2025-06-13 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customeragent_assigned_clients_and_more'),
        ('appointments', '0002_expertholiday_expertavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bu randevu için müşteri tarafından ödenen veya belirlenen toplam tutar.', max_digits=10, null=True, verbose_name='Randevu Ücreti'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_appointments', to='accounts.customeragent', verbose_name='Temsilci'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_appointments', to='accounts.expert', verbose_name='Uzman'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.BooleanField(default=False, help_text='Bu randevu için ödeme yapıldı mı?', verbose_name='Ödeme Durumu'),
        ),
    ]
