# Generated by Django 5.2.2 on 2025-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_amount_alter_appointment_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('filler', 'Dolgu Uygulaması'), ('botox', 'Botoks Uygulaması'), ('lip_blush', 'Dudak Renklendirme'), ('skin_care', 'Cilt Bakımı'), ('laser_hair_removal', 'Lazer Epilasyon'), ('chemical_peel', 'Kimyasal Peeling'), ('prp', 'PRP Tedavisi'), ('mesotherapy', 'Mezoterapi'), ('dermapen', 'Dermapen'), ('other', 'Diğer Hizmet')], default='other', help_text='Bu randevuda sunulan hizmetin türü.', max_length=50, verbose_name='Hizmet Tipi'),
        ),
    ]
