"""
Django settings for klinik_yonetim project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Üretim ortamında bu anahtarın çevresel değişkenlerden veya daha güvenli bir yöntemle alınması ŞARTTIR.
# Geliştirme için bu haliyle bırakılabilir.
SECRET_KEY = 'django-insecure-7#ge2&(991fk2*i*-h3wc6)^1$uotfgi2h#tky40zs@ck3#di6'

# SECURITY WARNING: don't run with debug turned on in production!
# Üretim ortamında DEBUG = False yapılmalıdır.
DEBUG = True

ALLOWED_HOSTS = [] # Geliştirme ortamında boş kalabilir. Üretimde IP adresleri veya alan adları buraya eklenmelidir.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Üçüncü Parti Uygulamalar
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.humanize',

    # Sizin özel uygulamalarınız burada olmalı:
    'accounts.apps.AccountsConfig',      # Özel kullanıcı modeli
    'appointments.apps.AppointmentsConfig',  # Randevu sistemi
    'payments.apps.PaymentsConfig',      # Ödeme sistemi (Doğru yerleştirilmiş)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Özel middleware'ınız burada, AuthenticationMiddleware'dan sonra olması mantıklı.
    'appointments.middleware.AppointmentCheckMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'klinik_yonetim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS' Django'nun şablonları arayacağı ana klasörü belirtir.
        # Bu, tüm uygulamaların ortak şablonlarını koyduğunuz yer olmalıdır (örneğin base.html, navbar.html vb.).
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        # 'APP_DIRS': True, her uygulamanın kendi 'templates' klasöründe de şablon aramasını sağlar.
        # Bu yüzden accounts/templates/accounts/login.html gibi yapılar çalışır.
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # DEBUG modunda hata ayıklama için faydalı
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_roles', 
                
            ],
        },
    },
]

WSGI_APPLICATION = 'klinik_yonetim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'klinik_db',
        'USER': 'postgres',
        'PASSWORD': '230477', # Üretim ortamında bu şifrenin çevresel değişkenlerden alınması ŞARTTIR.
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'  # Türkçe için

TIME_ZONE = 'Europe/Istanbul' # Türkiye için doğru zaman dilimi

USE_I18N = True # Uluslararasılaştırma desteğini etkinleştirir

# USE_L10N Django 4.0'dan itibaren kaldırılmıştır ve USE_I18N tarafından üstlenilmiştir.
# Eğer Django 4.0 ve üzeri kullanıyorsanız bu satırı kaldırabilirsiniz.
# USE_L10N = True 

USE_TZ = True # Zaman dilimi duyarlı tarih ve saatleri etkinleştirir (ÖNEMLİ!)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # Statik dosyalarınızın toplu olarak bulunduğu dizin
STATIC_ROOT = BASE_DIR / 'staticfiles' # Genellikle üretim için kullanılır

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'      # Özel kullanıcı modelinizin yolu (Doğru)

# URL Yönlendirmeleri
LOGIN_URL = '/hesap/giris/'                 # Giriş yapmayan kullanıcılar buraya yönlendirilir
LOGIN_REDIRECT_URL = '/appointments/randevu/liste/' # Başarılı giriş sonrası yönlendirme
LOGOUT_REDIRECT_URL = '/'                   # Çıkış sonrası yönlendirme

# Email ayarları (şifre sıfırlama vb. için)
# Üretim ortamında hassas bilgiler (EMAIL_HOST_PASSWORD) çevresel değişkenlerden alınmalıdır.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True # Güvenli bağlantı için TLS kullanır
EMAIL_HOST_USER = 'muratmurat77@gmail.com'
EMAIL_HOST_PASSWORD = 'Anka2304+' # GERÇEK BİR UYGULAMADA KESİNLİKLE BURADA OLMAZ!

# Crispy Forms ayarları
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django'da varsayılan mesaj depolama (genellikle değiştirilmez)
# MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage' 